openapi: 3.0.3
info:
  title: Account Management
  version: "1.0"
  contact:
    name: Scott McGowan
    url: http://github.com/evilmonkeyinc
    email: evilmonkeyinc@gmail.com
tags:
  - name: plugin
    description: a plugin used to extend the service
components:
  schemas:
    Error:
      $ref: "./components/error.yaml"
    PageDetails:
      $ref: "./components/page-details.yaml"
    Plugin:
      $ref: "./components/plugin.yaml"
paths:
  /plugins/list:
    $ref: "./paths/plugins.yaml#/paths/~1plugins~1list"
  /plugins/{name}:
    $ref: "./paths/plugins.yaml#/paths/~1plugins~1{name}"
servers:
  - url: "https://api.server.test/v1"
    description: local test server
