openapi: 3.0.3
info:
  title: Account Management
  version: "1.0"
  contact:
    name: Scott McGowan
    url: http://github.com/evilmonkeyinc
    email: evilmonkeyinc@gmail.com
tags:
  - name: plugin
    description: a plugin used to extend the service
  - name: users
    description: a user used to access the service
components:
  parameters:
    queryLimit:
      $ref: "./components/parameters/query-limit.yaml"
    queryPage:
      $ref: "./components/parameters/query-page.yaml"
  responses:
    "response404":
      $ref: "./components/responses/404.yaml"
    "response500":
      $ref: "./components/responses/500.yaml"
  schemas:
    Error:
      $ref: "./components/schemas/error.yaml"
    PageDetails:
      $ref: "./components/schemas/page-details.yaml"
    Plugin:
      $ref: "./components/schemas/plugin.yaml"
    ListPluginsResponse:
      $ref: "./components/schemas/plugins-list.yaml"
    User:
      $ref: "./components/schemas/user.yaml"
    ListUsersResponse:
      $ref: "./components/schemas/users-list.yaml"
paths:
  /plugins:
    $ref: "./paths/plugins.yaml#/paths/plugins"
  /plugins/{name}:
    $ref: "./paths/plugins.yaml#/paths/plugins~1{name}"
  /users:
    $ref: "./paths/users.yaml#/paths/users"
servers:
  - url: "https://api.server.test/v1"
    description: local test server
