openapi: 3.0.3
info:
  title: Account Management
  version: '1.0'
paths:
  /plugins/{name}:
    get:
      description: 'Get the specified plugin'
      parameters:
        - $ref: '#/components/parameters/plugin_name'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plugin'
  /plugins/list:
    get:
      description: 'list all supported plugins'
      parameters:
          - $ref: '#/components/parameters/limit'
          - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageDetails'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Plugin'
servers:
  - url: 'https://api.server.test/v1'
    description: local test server
components:
  schemas:
    PageDetails:
      type: object
      properties:
        limit:
          type: integer
        page:
          type: integer
        count: 
          type: integer
        total: 
          type: integer
        paging:
          type: object 
          properties:
            current:
              type: string
              format: url
            first:
              type: string
              format: url
            previous:
              type: string
              format: url
            next:
              type: string
              format: url
            last:
              type: string
              format: url
    Plugin:
      type: object
      properties:
        name:
          type: string
  parameters:
    plugin_name:
      name: name
      in: path
      required: true
      description: 'The name of the plugin'
      schema:
        type: string
    limit:
      name: limit
      in: query
      required: false
      description: 'The number of items to return to the query, defaults to 25'
      schema:
        type: integer
    page:
      name: page
      in: query
      required: false
      description: 'The index of the page to retrieve, defaults to 0'
      schema:
        type: integer

   